### ISSUE TITLE
Fallback to non AVX instructions when not available

### ISSUE THREAD

**Issue by brancz** [segmentio/parquet-go#189]
We recently ran into an issue (https://github.com/parca-dev/parca/issues/1062) where a user had an amd64 architecture CPU without AVX extensions. This caused a `SIGILL` (illegal instruction) when parquet-go attempts to use the `VPBROADCASTD` instruction:

https://github.com/segmentio/parquet-go/blob/ce6d4da96469907924d6f87b746ca9169b6604cc/bloom/filter_amd64.s#L110

I would suggest we use the [golang.org/x/sys/cpu](https://pkg.go.dev/golang.org/x/sys/cpu) package to detect if the SIMD instructions we want to use are available and fallback to pure go implementations when not.

The apache arrow project accomplishes this using global variables:

https://github.com/apache/arrow/blob/442b24b0b9cf11d45245564fa7448f1ca4931ae7/go/arrow/math/int64.go#L30

Which are set using init functions:

https://github.com/apache/arrow/blob/6240eae2189d938b4f98b8d8235146baed0246c5/go/arrow/math/math_amd64.go#L25-L33

I'm happy with any strategy that works, this is just one I've seen before.

**Comment by achille-roussel** [comment]
I tried the global function pointer approach used in Arrow but it has a significant impact on throughput:
```
name              old time/op    new time/op    delta
SplitBlockFilter    1.95µs ± 3%    2.54µs ± 5%  +30.28%  (p=0.000 n=9+10)

name              old speed      new speed      delta
SplitBlockFilter  4.10GB/s ± 3%  3.15GB/s ± 5%  -23.23%  (p=0.000 n=9+10)
```
I'll look into an alternative solution.

**Comment by javierhonduco** [comment]
Thanks for the fix, @achille-roussel!!

Unfortunately, it seems that `VPBROADCASTB` is also in the `bits/count_amd64.s` file, such as in here:

https://github.com/segmentio/parquet-go/blob/5ba9f0b2689269658f4de1cf0d4daf7759fd4708/internal/bits/count_amd64.s#L34

which won't work in CPUs that don't support avx2

```
[javierhonduco@localhost-live parca]$ grep avx2 /proc/cpuinfo
[javierhonduco@localhost-live parca]$ echo $?
1
```

The crashing stack-trace from Parca:

```
SIGILL: illegal instruction
PC=0x9ba295 m=3 sigcode=2
instruction bytes: 0xc4 0xe2 0x7d 0x78 0x44 0x24 0x20 0xc5 0xfe 0x6f 0x8 0xc5 0xfe 0x6f 0x50 0x20

goroutine 177 [running]:
github.com/segmentio/parquet-go/internal/bits.countByte({0xc010900000, 0x104, 0x100000}, 0x0)
	/home/javierhonduco/go/pkg/mod/github.com/segmentio/parquet-go@v0.0.0-20220527005452-bf1e4db66515/internal/bits/count_amd64.s:68 +0xf5 fp=0xc0014def18 sp=0xc0014def10 pc=0x9ba295
github.com/segmentio/parquet-go/internal/bits.CountByte(...)
	/home/javierhonduco/go/pkg/mod/github.com/segmentio/parquet-go@v0.0.0-20220527005452-bf1e4db66515/internal/bits/count.go:3
github.com/segmentio/parquet-go/encoding/rle.isZero(...)
	/home/javierhonduco/go/pkg/mod/github.com/segmentio/parquet-go@v0.0.0-20220527005452-bf1e4db66515/encoding/rle/rle.go:504
github.com/segmentio/parquet-go/encoding/rle.isZeroInt32({0xc010900000?, 0x1100000012?, 0x0?})
	/home/javierhonduco/go/pkg/mod/github.com/segmentio/parquet-go@v0.0.0-20220527005452-bf1e4db66515/encoding/rle/rle.go:512 +0x6f fp=0xc0014def70 sp=0xc0014def18 pc=0xaa618f
github.com/segmentio/parquet-go/encoding/rle.encodeInt32({0xc000306240, 0x1, 0x240}, {0xc010900000?, 0x41, 0x41?}, 0x0)
	/home/javierhonduco/go/pkg/mod/github.com/segmentio/parquet-go@v0.0.0-20220527005452-bf1e4db66515/encoding/rle/rle.go:222 +0x11f fp=0xc0014df240 sp=0xc0014def70 pc=0xaa35bf
github.com/segmentio/parquet-go/encoding/rle.(*DictionaryEncoding).EncodeInt32(0x5a7ffa0, {0xc000306240?, 0x104?, 0x100000?}, {0xc010900000?, 0xaed482?, 0x0?})
	/home/javierhonduco/go/pkg/mod/github.com/segmentio/parquet-go@v0.0.0-20220527005452-bf1e4db66515/encoding/rle/dictionary.go:28 +0x265 fp=0xc0014df340 sp=0xc0014df240 pc=0xaa10a5
github.com/segmentio/parquet-go.indexedPageType.Encode({0xb196d3?}, {0xc000306240?, 0x0?, 0x0?}, {0xc010900000?, 0xc010b00000?, 0xc00e948090?}, {0x3f79e88?, 0x5a7ffa0?})
	/home/javierhonduco/go/pkg/mod/github.com/segmentio/parquet-go@v0.0.0-20220527005452-bf1e4db66515/dictionary.go:1024 +0x3a fp=0xc0014df388 sp=0xc0014df340 pc=0xae1eda
github.com/segmentio/parquet-go.(*writerBuffers).encode(0xc00a7e4120, {0x3f75278, 0xc00e948090}, {0x3f79e88, 0x5a7ffa0})
	/home/javierhonduco/go/pkg/mod/github.com/segmentio/parquet-go@v0.0.0-20220527005452-bf1e4db66515/writer.go:765 +0xa2 fp=0xc0014df3f0 sp=0xc0014df388 pc=0xb19c22
github.com/segmentio/parquet-go.(*writerColumn).writeBufferedPage(0xc010774000, {0x3f75278, 0xc00e948090})
	/home/javierhonduco/go/pkg/mod/github.com/segmentio/parquet-go@v0.0.0-20220527005452-bf1e4db66515/writer.go:1060 +0x125 fp=0xc0014df590 sp=0xc0014df3f0 pc=0xb1aec5
github.com/segmentio/parquet-go.(*writerColumn).flush(0xc010774000)
	/home/javierhonduco/go/pkg/mod/github.com/segmentio/parquet-go@v0.0.0-20220527005452-bf1e4db66515/writer.go:882 +0xaf fp=0xc0014df5f0 sp=0xc0014df590 pc=0xb1a16f
github.com/segmentio/parquet-go.(*writer).writeRowGroup(0xc01075d500, 0xc001060380?, {0x0, 0x0, 0x0})
	/home/javierhonduco/go/pkg/mod/github.com/segmentio/parquet-go@v0.0.0-20220527005452-bf1e4db66515/writer.go:548 +0x1e5 fp=0xc0014df8b8 sp=0xc0014df5f0 pc=0xb17e05
github.com/segmentio/parquet-go.(*writer).flush(...)
	/home/javierhonduco/go/pkg/mod/github.com/segmentio/parquet-go@v0.0.0-20220527005452-bf1e4db66515/writer.go:442
github.com/segmentio/parquet-go.(*writer).close(0xc01075d500)
	/home/javierhonduco/go/pkg/mod/github.com/segmentio/parquet-go@v0.0.0-20220527005452-bf1e4db66515/writer.go:429 +0x3d fp=0xc0014df8f0 sp=0xc0014df8b8 pc=0xb1737d
github.com/segmentio/parquet-go.(*Writer).Close(...)
	/home/javierhonduco/go/pkg/mod/github.com/segmentio/parquet-go@v0.0.0-20220527005452-bf1e4db66515/writer.go:95
github.com/polarsignals/arcticdb/dynparquet.(*Schema).SerializeBuffer(0xc00129b000?, 0xc00105e280)
	/home/javierhonduco/go/pkg/mod/github.com/polarsignals/arcticdb@v0.0.0-20220527134701-450025ff363c/dynparquet/schema.go:402 +0x250 fp=0xc0014df9a8 sp=0xc0014df8f0 pc=0xb3c270
github.com/polarsignals/arcticdb.(*Table).InsertBuffer(0xc00100a0c0, {0x3f5d770, 0xc0000eb6e0}, 0x3?)
	/home/javierhonduco/go/pkg/mod/github.com/polarsignals/arcticdb@v0.0.0-20220527134701-450025ff363c/table.go:188 +0x39 fp=0xc0014df9f8 sp=0xc0014df9a8 pc=0xc9cf99
github.com/parca-dev/parca/pkg/parcacol.InsertProfileIntoTable({0x3f5d770, 0xc0000eb6e0}, {0x3f3b360, 0xc0013af770}, {0x3f49a90, 0xc00100a0c0}, {0xc00acdbc80, 0x3, 0x3}, 0xc00ac59380)
	/home/javierhonduco/code/parca/pkg/parcacol/parcacol.go:45 +0xe2 fp=0xc0014dfa40 sp=0xc0014df9f8 pc=0x28cfe42
github.com/parca-dev/parca/pkg/profilestore.(*ProfileColumnStore).WriteRaw(0xc00100a200, {0x3f5d6c8?, 0xc001760e80?}, 0xc00acdbc20)
	/home/javierhonduco/code/parca/pkg/profilestore/profilecolumnstore.go:126 +0xcb9 fp=0xc0014dfcc0 sp=0xc0014dfa40 pc=0x28d5df9
github.com/parca-dev/parca/pkg/scrape.(*scrapeLoop).run(0xc001009180, 0xc000e12098?, 0x52d2a6?, 0x0)
	/home/javierhonduco/code/parca/pkg/scrape/scrape.go:484 +0xe9f fp=0xc0014dffb0 sp=0xc0014dfcc0 pc=0x2902a7f
github.com/parca-dev/parca/pkg/scrape.(*scrapePool).sync.func3()
	/home/javierhonduco/code/parca/pkg/scrape/scrape.go:261 +0x35 fp=0xc0014dffe0 sp=0xc0014dffb0 pc=0x2900df5
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0014dffe8 sp=0xc0014dffe0 pc=0x46d1c1
created by github.com/parca-dev/parca/pkg/scrape.(*scrapePool).sync
	/home/javierhonduco/code/parca/pkg/scrape/scrape.go:261 +0x3bc
[...]
```

**Comment by javierhonduco** [comment]
Thanks so much! Happy to help with anything! 😄

**Comment by achille-roussel** [comment]
I realized I forgot to mention this, as a workaround  you can build with `-tags purego` to disable all AVX optimizations.

**Comment by achille-roussel** [comment]
#224 should have fixed the remaining issue, but let me know if you are still running into problems.

**Comment by javierhonduco** [comment]
Thanks for the PR, and sorry for the delay while I was away. I just tried with `edd371b528ffa7d9b637160d4fbd3b88f82698fa` and I _think_ that `encodeBytesBitpack`  is still using avx2

```
SIGILL: illegal instruction
PC=0xaa6049 m=8 sigcode=2
instruction bytes: 0xc4 0x62 0xba 0xf5 0xc7 0x4c 0x89 0x0 0x48 0x1 0xd0 0x48 0xff 0xc6 0x48 0x39

goroutine 3462 [running]:
github.com/segmentio/parquet-go/encoding/rle.encodeBytesBitpack({0xc00b20e604, 0x13, 0x28}, {0xc006e52178, 0x2, 0x3ea}, 0x1)
	/home/javierhonduco/go/pkg/mod/github.com/segmentio/parquet-go@v0.0.0-20220616233901-edd371b528ff/encoding/rle/rle_amd64.s:49 +0x29 fp=0xc000e9b578 sp=0xc000e9b570 pc=0xaa6049
github.com/segmentio/parquet-go/encoding/rle.appendBitPackedBytes({0xc0096f20d8?, 0x3?, 0x0?}, {0xc006e52178?, 0x0?, 0x3ea?}, 0x1?)
	/home/javierhonduco/go/pkg/mod/github.com/segmentio/parquet-go@v0.0.0-20220616233901-edd371b528ff/encoding/rle/rle.go:451 +0x1fc fp=0xc000e9b610 sp=0xc000e9b578 pc=0xaa573c
github.com/segmentio/parquet-go/encoding/rle.encodeBytes({0xc0096f20d8, 0x0, 0x16}, {0xc006e52000, 0x20cb, 0x0?}, 0x1)
	/home/javierhonduco/go/pkg/mod/github.com/segmentio/parquet-go@v0.0.0-20220616233901-edd371b528ff/encoding/rle/rle.go:175 +0x5b5 fp=0xc000e9b6d0 sp=0xc000e9b610 pc=0xaa2b35
github.com/segmentio/parquet-go/encoding/rle.(*Encoding).EncodeLevels(0x5867c60, {0xc0096f20d8?, 0x0?, 0x0?}, {0xc006e52000?, 0x0?, 0x0?})
	/home/javierhonduco/go/pkg/mod/github.com/segmentio/parquet-go@v0.0.0-20220616233901-edd371b528ff/encoding/rle/rle.go:45 +0x4c fp=0xc000e9b750 sp=0xc000e9b6d0 pc=0xaa160c
github.com/segmentio/parquet-go.(*writerBuffers).encodeDefinitionLevels(0xc008806120, {0x3f418d0?, 0xc0002f7d10?}, 0x0?)
	/home/javierhonduco/go/pkg/mod/github.com/segmentio/parquet-go@v0.0.0-20220616233901-edd371b528ff/writer.go:733 +0x93 fp=0xc000e9b7b0 sp=0xc000e9b750 pc=0xb21273
github.com/segmentio/parquet-go.(*writerColumn).writeBufferedPage(0xc008878840, {0x3f418d0, 0xc0002f7d10})
	/home/javierhonduco/go/pkg/mod/github.com/segmentio/parquet-go@v0.0.0-20220616233901-edd371b528ff/writer.go:1064 +0xeb fp=0xc000e9b950 sp=0xc000e9b7b0 pc=0xb22aab
github.com/segmentio/parquet-go.(*writerColumn).flush(0xc008878840)
	/home/javierhonduco/go/pkg/mod/github.com/segmentio/parquet-go@v0.0.0-20220616233901-edd371b528ff/writer.go:886 +0xaf fp=0xc000e9b9b0 sp=0xc000e9b950 pc=0xb21d0f
github.com/segmentio/parquet-go.(*writer).writeRowGroup(0xc00a145680, 0x0?, {0x0, 0x0, 0x0})
	/home/javierhonduco/go/pkg/mod/github.com/segmentio/parquet-go@v0.0.0-20220616233901-edd371b528ff/writer.go:552 +0x1e5 fp=0xc000e9bc78 sp=0xc000e9b9b0 pc=0xb1f9a5
github.com/segmentio/parquet-go.(*writer).flush(...)
	/home/javierhonduco/go/pkg/mod/github.com/segmentio/parquet-go@v0.0.0-20220616233901-edd371b528ff/writer.go:446
github.com/segmentio/parquet-go.(*writer).close(0xc00a145680)
	/home/javierhonduco/go/pkg/mod/github.com/segmentio/parquet-go@v0.0.0-20220616233901-edd371b528ff/writer.go:433 +0x3d fp=0xc000e9bcb0 sp=0xc000e9bc78 pc=0xb1ef1d
github.com/segmentio/parquet-go.(*Writer).Close(...)
	/home/javierhonduco/go/pkg/mod/github.com/segmentio/parquet-go@v0.0.0-20220616233901-edd371b528ff/writer.go:99
```

**Comment by javierhonduco** [comment]
Started trying to peel some of the layers in parquet-go in https://github.com/javierhonduco/parquet-go/commit/78bcbc7a3cd156313821c6f355e754cd5144ec03, last issue that popped out:

```
SIGILL: illegal instruction
PC=0x7af662 m=0 sigcode=2
instruction bytes: 0x4c 0xf 0x38 0xf0 0x14 0x38 0x4c 0xf 0x38 0xf0 0x5c 0x38 0x8 0x4d 0x89 0xd4

goroutine 877 [running]:
github.com/segmentio/parquet-go.dictionaryBoundsBE128({0xc0002feba0, 0x1, 0x1}, {0xc0001336c0, 0x1, 0x64})
	/home/javierhonduco/code/parquet-go/dictionary_amd64.s:601 +0x42 fp=0xc0004a9888 sp=0xc0004a9880 pc=0x7af662
github.com/segmentio/parquet-go.(*be128Dictionary).bounds(0x0?, {0xc0001336c0?, 0x1?, 0x0?})
	/home/javierhonduco/code/parquet-go/dictionary_amd64.go:138 +0x4b fp=0xc0004a98e0 sp=0xc0004a9888 pc=0x75e6cb
github.com/segmentio/parquet-go.(*be128Dictionary).Bounds(0xc0001e86c0, {0xc0001336c0?, 0xc0004a99f8?, 0x40f185?})
	/home/javierhonduco/code/parquet-go/dictionary.go:1054 +0x56 fp=0xc0004a9958 sp=0xc0004a98e0 pc=0x75b2d6
github.com/segmentio/parquet-go.(*indexedPage).Bounds(0xc00053e540)
	/home/javierhonduco/code/parquet-go/dictionary.go:1152 +0x9c fp=0xc0004a9a08 sp=0xc0004a9958 pc=0x75bb5c
github.com/segmentio/parquet-go.(*optionalPage).Bounds(0x0?)
	/home/javierhonduco/code/parquet-go/page.go:326 +0x69 fp=0xc0004a9ac8 sp=0xc0004a9a08 pc=0x76a1c9
github.com/segmentio/parquet-go_test.testBuffer(0xc0001356c0, {0x7fa81824a3c0, 0xc000245e80}, 0xc0000fa990, {0xa5a090?, 0xe28240?}, {0xde8280, 0x1, 0x1?}, 0x9bbaa0)
	/home/javierhonduco/code/parquet-go/buffer_test.go:298 +0x5ec fp=0xc0004a9eb0 sp=0xc0004a9ac8 pc=0x7e050c
github.com/segmentio/parquet-go_test.TestBuffer.func1.1.1.1.1(0xc0000e3d40?)
	/home/javierhonduco/code/parquet-go/buffer_test.go:223 +0x147 fp=0xc0004a9f70 sp=0xc0004a9eb0 pc=0x7df9a7
testing.tRunner(0xc0001356c0, 0xc00053e690)
	/usr/lib/golang/src/testing/testing.go:1439 +0x102 fp=0xc0004a9fc0 sp=0xc0004a9f70 pc=0x50a002
testing.(*T).Run.func1()
	/usr/lib/golang/src/testing/testing.go:1486 +0x2a fp=0xc0004a9fe0 sp=0xc0004a9fc0 pc=0x50aeaa
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0004a9fe8 sp=0xc0004a9fe0 pc=0x46a4e1
created by testing.(*T).Run
	/usr/lib/golang/src/testing/testing.go:1486 +0x35f
```

https://github.com/segmentio/parquet-go/blob/055039b0e61a7ef512b1f96dedd65bf42c45070d/dictionary_amd64.s#L601

I am not sure what's going on here. Checking the current instructions for all threads of the process doesn't show anything interesting, in fact, I think it might be wrong?

```
(gdb) thread apply all display/i $pc

Thread 8 (LWP 200985):
18: x/i $pc

=> 0x46bdfd:	add    %al,(%rax)

Thread 7 (LWP 200979):
19: x/i $pc

=> 0x46bdfd:	add    %al,(%rax)

Thread 6 (LWP 200982):
20: x/i $pc

=> 0x46bdfd:	add    %al,(%rax)

Thread 5 (LWP 200983):
21: x/i $pc

=> 0x46bdfd:	add    %al,(%rax)

Thread 4 (LWP 200981):
22: x/i $pc

=> 0x46bdfd:	add    %al,(%rax)

Thread 3 (LWP 200984):
23: x/i $pc

=> 0x46bdfd:	add    %al,(%rax)

Thread 2 (LWP 200980):
24: x/i $pc

=> 0x46bdfd:	add    %al,(%rax)

Thread 1 (LWP 200986):
25: x/i $pc

=> 0x46be61:	add    %al,(%rax)
```

Do you know what can be causing this? Thanks in advance!!

**Comment by achille-roussel** [comment]
Hello @javierhonduco 

Do you happen to know what CPU you're running on?

**Comment by javierhonduco** [comment]
A pretty old Ivy Bridge 😄  [`Intel(R) Core(TM) i5-3450 CPU @ 3.10GHz`](https://www.intel.com/content/www/us/en/products/sku/65511/intel-core-i53450-processor-6m-cache-up-to-3-50-ghz/specifications.html). If you are not planning to support it, I totally understand it :)

**Comment by achille-roussel** [comment]
If Go supports it we should, I just wanted to learn what instruction sets it had to better handle these issues moving forward.

**Comment by javierhonduco** [comment]
Just tried https://github.com/javierhonduco/parquet-go/commit/78bcbc7a3cd156313821c6f355e754cd5144ec03 which includes your changes (https://github.com/segmentio/parquet-go/commit/f88e58831030a7d7f2ded13122b51e963435bc88) and can confirm that the tests pass now! Let me know if you would be ok with a PR with these changes and I will be happy to cut a PR 😄
