### ISSUE TITLE
Panic in indexedColumnBuffer.Less

### ISSUE THREAD

**Issue by metalmatze** [segmentio/parquet-go#276]
Hey, currently I'm seeing a panic in parquet-go.

More specifically it seems to be panicking when sorting a buffer here:
https://github.com/segmentio/parquet-go/blob/7691e3e37eea2b18b560a61cfc6636b615e0ffc6/dictionary.go#L1251-L1255

```
panic: runtime error: index out of range [1] with length 0 [recovered]
  panic: runtime error: index out of range [1] with length 0

goroutine 1832 [running]:
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End·dwrap·12()
  go.opentelemetry.io/otel/sdk@v1.7.0/trace/span.go:359 +0x2a
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc000edd200, {0x0, 0x0, 0x0})
  go.opentelemetry.io/otel/sdk@v1.7.0/trace/span.go:398 +0x9a2
panic({0x239f420, 0xc000b46198})
  runtime/panic.go:1047 +0x266
github.com/segmentio/parquet-go.(*indexedColumnBuffer).Less(0x0, 0x1c, 0x0)
  github.com/segmentio/parquet-go@v0.0.0-20220630161706-7691e3e37eea/dictionary.go:1252 +0x15a
github.com/segmentio/parquet-go.(*Buffer).Less(0x989680, 0x20000fd, 0xc000717cf0)
  github.com/segmentio/parquet-go@v0.0.0-20220630161706-7691e3e37eea/buffer.go:158 +0x83
sort.insertionSort({0x28a1ce0, 0xc00118f5f0}, 0x0, 0x2)
  sort/sort.go:40 +0xb1
sort.quickSort({0x28a1ce0, 0xc00118f5f0}, 0x1, 0xffef000000fd, 0xc000077908)
  sort/sort.go:222 +0x171
sort.Sort({0x28a1ce0, 0xc00118f5f0})
  sort/sort.go:231 +0x53
github.com/polarsignals/frostdb/dynparquet.(*Buffer).Sort(...)
  github.com/polarsignals/frostdb@v0.0.0-20220705133026-06d6050cd153/dynparquet/schema.go:273
  ```
  
It's totally possible that there is something wrong further up in FrostDB and the way we're calling the sort on the buffer? 
It could also be possible that we're sorting an empty buffer? I'm going to add a check to not sort if the buffer is empty and instead return early.

**Comment by achille-roussel** [comment]
Thanks for reporting the issue!

There is a `Len() int` method on `sort.Interface` which is used by `sort.Sort` and should guard against calling `Less` if the input is empty, so I'm thinking this might rather be an implementation bug in parquet-go.

Would you happen to have a way to reproduce the issue that you could share?

**Comment by achille-roussel** [comment]
Hello @metalmatze, I was curious to learn whether you have made progress on this issue.

Let me know!

**Comment by achille-roussel** [comment]
Hello,

I wanted to circle back here to see if this was still an issue.
