### ISSUE TITLE
Calling Deconstruct on Schema, passing Struct that wasn't used to create schema, panics.

### ISSUE THREAD

**Issue by abraithwaite** [segmentio/parquet-go#318]
I will work on a better reproduction scenario shortly, just trying to get this somewhere for posterity.  Fairly low priority.

I think we can at least give a better message in this scenario, instead of trying to blindly parse it.

e.g. this panics.
```
a := parquet.SchemaOf(MyStructA{})

a.Deconstruct(nil, MyStructB{})
```

```
panic: reflect: Field index out of range [recovered]
        panic: reflect: Field index out of range

goroutine 5 [running]:
testing.tRunner.func1.2({0x102978ea0, 0x102a536c0})
        /opt/homebrew/Cellar/go/1.19/libexec/src/testing/testing.go:1396 +0x1c8
testing.tRunner.func1()
        /opt/homebrew/Cellar/go/1.19/libexec/src/testing/testing.go:1399 +0x378
panic({0x102978ea0, 0x102a536c0})
        /opt/homebrew/Cellar/go/1.19/libexec/src/runtime/panic.go:884 +0x204
reflect.Value.Field({0x1029f8a60?, 0x102e1da20?, 0x2?}, 0x1?)
        /opt/homebrew/Cellar/go/1.19/libexec/src/reflect/value.go:1270 +0xb0
github.com/segmentio/parquet-go.(*structField).Value(0x1400007fa70?, {0x1029f8a60?, 0x102e1da20?, 0x0?})
        /Users/abraithwaite/Projects/parquet-go/schema.go:439 +0x228
github.com/segmentio/parquet-go.deconstructFuncOfGroup.func1({0x0?, 0x1?, 0x1?}, {0x0?, 0x1?, 0x4?}, {0x1029f8a60?, 0x102e1da20?, 0x0?})
        /Users/abraithwaite/Projects/parquet-go/row.go:478 +0xf8
github.com/segmentio/parquet-go.(*Schema).Deconstruct(0x1400010a300, {0x0?, 0x0, 0x0}, {0x1029f8a60?, 0x102e1da20?})
        /Users/abraithwaite/Projects/parquet-go/schema.go:233 +0x18c
github.com/segmentio/parquet-go_test.TestConvert.func1(0x1400016e680)
        /Users/abraithwaite/Projects/parquet-go/convert_test.go:150 +0xc4
testing.tRunner(0x1400016e680, 0x140000717c0)
        /opt/homebrew/Cellar/go/1.19/libexec/src/testing/testing.go:1446 +0x10c
created by testing.(*T).Run
        /opt/homebrew/Cellar/go/1.19/libexec/src/testing/testing.go:1493 +0x300
exit status 2
FAIL    github.com/segmentio/parquet-go 0.645s
```

**Comment by abraithwaite** [comment]
I'm not sure there's a good way to verify whether or not the schema is the one intended for the `Reconstruct`/`Deconstruct` call since verifying that the schema of `value` is equal to the schema of the method receiver requires a recursive traversal of the struct, which doesn't seem efficient to do for every call to this function.
