### ISSUE TITLE
Parquet files containing BYTE_ARRAY column fields written by Benthos not readable by either pyarrow or fastparquet

### ISSUE THREAD

**Issue by akai-katto** [segmentio/parquet-go#325]
This bug was raised from [benthos](https://github.com/benthosdev/benthos) project. 

Using Benthos, I have two tables, one named "ID" which only contains columns containing INT64, and "person", which contains strings as well as INT64s. 

What the code looks like:

Using benthos to extract information from "person" table looks like this, 

```
input:
  sql_select:
    driver: postgres
    dsn: postgres://username:password@localhost:5432/default_database?sslmode=disable
    table: person
    columns: [ '*' ]
buffer:
  none: {}
output:
  aws_s3:
    bucket: < BUCKET NAME HERE > 
    region: < REGION HERE > 
    credentials:
      profile: < PROFILE HERE > 
    path: 'stuff/${! timestamp_unix() }-${! uuid_v4() }.parquet'
    batching:
      count: 1000
      period: 10s
      processors:
        - parquet_encode:
            schema:
              - name: "name"
                type: BYTE_ARRAY
              - name: "age"
                type: INT64
              - name: "lastupdated"
                type: BYTE_ARRAY
            default_compression: zstd
```

and attempting to load the resulting parquet file written to s3 prints this: 

```
import pandas as pd
test = pd.read_parquet('not_working.parquet', engine='pyarrow')
print(test)

-> 

Traceback (most recent call last):
  File "/Users/tyler/PycharmProjects/sieve_s3/sort_me.py", line 2, in <module>
    test = pd.read_parquet('not_working.parquet', engine='pyarrow')
  File "/Users/tyler/PycharmProjects/sieve_s3/venv/lib/python3.8/site-packages/pandas/io/parquet.py", line 493, in read_parquet
    return impl.read(
  File "/Users/tyler/PycharmProjects/sieve_s3/venv/lib/python3.8/site-packages/pandas/io/parquet.py", line 240, in read
    result = self.api.parquet.read_table(
  File "/Users/tyler/PycharmProjects/sieve_s3/venv/lib/python3.8/site-packages/pyarrow/parquet/__init__.py", line 2827, in read_table
    return dataset.read(columns=columns, use_threads=use_threads,
  File "/Users/tyler/PycharmProjects/sieve_s3/venv/lib/python3.8/site-packages/pyarrow/parquet/__init__.py", line 2473, in read
    table = self._dataset.to_table(
  File "pyarrow/_dataset.pyx", line 331, in pyarrow._dataset.Dataset.to_table
  File "pyarrow/_dataset.pyx", line 2577, in pyarrow._dataset.Scanner.to_table
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 115, in pyarrow.lib.check_status
OSError: Not yet implemented: DecodeArrow for DeltaLengthByteArrayDecoder.

Process finished with exit code 1
```

However, if only done using INT64, everything works flawlessly. 

```
...
    batching:
      count: 1000
      period: 10s
      processors:
        - parquet_encode:
            schema:
              - name: "age"
                type: INT64
              - name: "id"
                type: INT64
            default_compression: zstd
        - catch:
          - log:
              level: ERROR
              message: "Schema validation failed due to: ${!error()}"
          - bloblang: 'root = deleted()' # Drop messages that fail
```

```
import pandas as pd
test = pd.read_parquet('working.parquet', engine='pyarrow')
print(test)

-> 

   age  id
0   15  10
1   30  20

Process finished with exit code 0
```

Files mentioned: 

[parquet_files.zip](https://github.com/segmentio/parquet-go/files/9456584/parquet_files.zip)

Hardware: 

MBP 2021 M1

---

I don't have any educated guesses other than the BYTE_ARRAY conversion from TEXT to bytes isn't being done in UTF-8.

**Comment by akai-katto** [comment]
nmind might not be a parquet-go issue
