### ISSUE TITLE
Slice out of bounds panics while using dictionaries

### ISSUE THREAD

**Issue by joe-elliott** [segmentio/parquet-go#332]
During larger queries we see a number of different panics related to slice out of bounds in dictionaries.

Example 1:
```panic: index out of bounds

goroutine 4690 [running]:
github.com/segmentio/parquet-go.errno.check(...)
	/home/joe/dev/joe-elliott/tempo/vendor/github.com/segmentio/parquet-go/errors.go:65
github.com/segmentio/parquet-go.(*uint64Dictionary).bounds(0x1649ce5337840846?, {0xc083856000?, 0xc1c29b2e112ce4d?, 0x0?})
	/home/joe/dev/joe-elliott/tempo/vendor/github.com/segmentio/parquet-go/dictionary_amd64.go:134 +0x99
github.com/segmentio/parquet-go.(*uint64Dictionary).Bounds(0xc090e5c2c0, {0xc083856000?, 0xa0bde1c12?, 0x3632e40?})
	/home/joe/dev/joe-elliott/tempo/vendor/github.com/segmentio/parquet-go/dictionary.go:1072 +0x45
github.com/segmentio/parquet-go.(*indexedPage).Bounds(0xc07096a7e0)
	/home/joe/dev/joe-elliott/tempo/vendor/github.com/segmentio/parquet-go/dictionary.go:1293 +0x9c
github.com/grafana/tempo/pkg/parquetquery.(*IntBetweenPredicate).KeepPage(0xc06e347b80, {0x257c0f0?, 0xc07096a810?})
	/home/joe/dev/joe-elliott/tempo/pkg/parquetquery/predicates.go:176 +0x6b
github.com/grafana/tempo/pkg/parquetquery.(*InstrumentedPredicate).KeepPage(0xc06e599140, {0x257c0f0?, 0xc07096a810?})
	/home/joe/dev/joe-elliott/tempo/pkg/parquetquery/predicates.go:208 +0x43
github.com/grafana/tempo/pkg/parquetquery.(*ColumnIterator).iterate.func3({0x257b3e0, 0xc06b23be60}, {0x2565588, 0xc06e59a990}, 0xc0600cdf58, 0xc0600cded0, 0xc060c9b400, {0xc06ea4e000, 0x3e8, 0x3e8}, ...)
	/home/joe/dev/joe-elliott/tempo/pkg/parquetquery/iters.go:346 +0x24b
github.com/grafana/tempo/pkg/parquetquery.(*ColumnIterator).iterate(0xc060c9b400, {0x2565588, 0xc060e01bf0}, 0x0?)
	/home/joe/dev/joe-elliott/tempo/pkg/parquetquery/iters.go:403 +0x4cf
created by github.com/grafana/tempo/pkg/parquetquery.NewColumnIterator
	/home/joe/dev/joe-elliott/tempo/pkg/parquetquery/iters.go:266 +0x245
```

Example 2:
```
panic: runtime error: slice bounds out of range [:65] with capacity 64

goroutine 10740 [running]:
github.com/segmentio/parquet-go.newUint64Dictionary(...)
	/home/joe/dev/joe-elliott/tempo/vendor/github.com/segmentio/parquet-go/dictionary.go:1012
github.com/segmentio/parquet-go.(*intType).NewDictionary(0xc0888dbbc0, 0x30, 0x41, {0x3, 0x0, {0xc07b87ea00, 0x1f8, 0x200}, {0x0, 0x0, ...}})
	/home/joe/dev/joe-elliott/tempo/vendor/github.com/segmentio/parquet-go/type.go:794 +0x593
github.com/segmentio/parquet-go.(*Column).decodeDictionary(0xc082ae1e10, {0x1310920?}, 0xc081e53890?, 0x522f7b98?)
	/home/joe/dev/joe-elliott/tempo/vendor/github.com/segmentio/parquet-go/column.go:744 +0x4f4
github.com/segmentio/parquet-go.(*filePages).readDictionaryPage(0xc09cb1bd60, 0xc08739f620?, 0xc08739f620?)
	/home/joe/dev/joe-elliott/tempo/vendor/github.com/segmentio/parquet-go/file.go:578 +0x3f
github.com/segmentio/parquet-go.(*filePages).ReadPage(0xc09cb1bd60)
	/home/joe/dev/joe-elliott/tempo/vendor/github.com/segmentio/parquet-go/file.go:514 +0x145
github.com/grafana/tempo/pkg/parquetquery.(*ColumnIterator).iterate.func3({0x257b3e0, 0xc0a89ffe60}, {0x2565588, 0xc05bef78f0}, 0xc0522f7f58, 0xc0522f7ed0, 0xc06037f380, {0xc052a62000, 0x3e8, 0x3e8}, ...)
	/home/joe/dev/joe-elliott/tempo/pkg/parquetquery/iters.go:329 +0x173
github.com/grafana/tempo/pkg/parquetquery.(*ColumnIterator).iterate(0xc06037f380, {0x2565588, 0xc094c38ed0}, 0xc040c05560?)
	/home/joe/dev/joe-elliott/tempo/pkg/parquetquery/iters.go:403 +0x4cf
created by github.com/grafana/tempo/pkg/parquetquery.NewColumnIterator
	/home/joe/dev/joe-elliott/tempo/pkg/parquetquery/iters.go:266 +0x245
```

Example 3:
```
panic: runtime error: slice bounds out of range [:19763617] with capacity 237567

goroutine 12226 [running]:
github.com/segmentio/parquet-go/encoding/rle.decodeInt32({0xc0946d5000?, 0xc0946d5000?, 0x6530?}, {0xc07fd80001, 0x5aa, 0x39fff}, 0x13)
	/home/joe/dev/joe-elliott/tempo/vendor/github.com/segmentio/parquet-go/encoding/rle/rle.go:367 +0xa1f
github.com/segmentio/parquet-go/encoding/rle.(*DictionaryEncoding).DecodeInt32(0x3664940, {0xc0946d5000?, 0x257e8d0?, 0xc0a3e7c7b0?}, {0xc07fd80000, 0x5ab, 0x3a000})
	/home/joe/dev/joe-elliott/tempo/vendor/github.com/segmentio/parquet-go/encoding/rle/dictionary.go:35 +0xad
github.com/segmentio/parquet-go/encoding.DecodeInt32({0x2, 0x0, {0xc0946d5000, 0x6530, 0x7000}, {0x0, 0x0, 0x0}}, {0xc07fd80000, 0x5ab, ...}, ...)
	/home/joe/dev/joe-elliott/tempo/vendor/github.com/segmentio/parquet-go/encoding/values.go:279 +0xc2
github.com/segmentio/parquet-go.indexedPageType.Decode({0x38?}, {0x2, 0x0, {0xc0946d5000, 0x6530, 0x7000}, {0x0, 0x0, 0x0}}, {0xc07fd80000, ...}, ...)
	/home/joe/dev/joe-elliott/tempo/vendor/github.com/segmentio/parquet-go/dictionary.go:1327 +0x108
github.com/segmentio/parquet-go.(*Column).decodeDataPage(0xc06f9149c0, {0x2576820?, 0xc0a3b84990?}, 0xca6, 0x0, 0x0, 0xc0a3e7c960, {0x25776c0?, 0xc0a3a66940})
	/home/joe/dev/joe-elliott/tempo/vendor/github.com/segmentio/parquet-go/column.go:629 +0x625
github.com/segmentio/parquet-go.(*Column).decodeDataPageV2(0xc06f9149c0, {0xc077dc4420?}, 0x0?, {0x25776c0, 0xc0a3a66940}, 0x7a879470?)
	/home/joe/dev/joe-elliott/tempo/vendor/github.com/segmentio/parquet-go/column.go:594 +0x60a
github.com/segmentio/parquet-go.(*filePages).readDataPageV2(0xc0a413c040?, 0xc0a3e7c930?, 0xc0a3e7c930?)
	/home/joe/dev/joe-elliott/tempo/vendor/github.com/segmentio/parquet-go/file.go:610 +0xa9
github.com/segmentio/parquet-go.(*filePages).ReadPage(0xc0a413c000)
	/home/joe/dev/joe-elliott/tempo/vendor/github.com/segmentio/parquet-go/file.go:507 +0xe5
github.com/grafana/tempo/pkg/parquetquery.(*ColumnIterator).iterate.func3({0x257b3e0, 0xc0674b37a0}, {0x2565588, 0xc06f23d590}, 0xc05bf77f58, 0xc05bf77ed0, 0xc060a1be00, {0xc0700c0000, 0x3e8, 0x3e8}, ...)
	/home/joe/dev/joe-elliott/tempo/pkg/parquetquery/iters.go:329 +0x173
github.com/grafana/tempo/pkg/parquetquery.(*ColumnIterator).iterate(0xc060a1be00, {0x2565588, 0xc08451c630}, 0xc065306fa0?)
	/home/joe/dev/joe-elliott/tempo/pkg/parquetquery/iters.go:403 +0x4cf
created by github.com/grafana/tempo/pkg/parquetquery.NewColumnIterator
	/home/joe/dev/joe-elliott/tempo/pkg/parquetquery/iters.go:266 +0x245
```

These panics are all occurring on tip of main (https://github.com/segmentio/parquet-go/commit/f812768dfa62ced67e9c8591183bf33e8eb35bff) but were also occurring before that.

**Comment by achille-roussel** [comment]
Hello @joe-elliott, thanks for reporting!

If possible, could you share files that trigger these panics? These would be extremely valuable to resolve the issues.

**Comment by joe-elliott** [comment]
> I'm also curious if you know when the files were created? Or know which parquet-go version was used to create the files?
@mdisibio would be the most likely to know the answer to this.

> If possible, could you share files that trigger these panics? These would be extremely valuable to resolve the issues.
I spent some time trying to reproduce with something smaller than our complete query engine. I will continue tomorrow and hopefully have something to share.

**Comment by joe-elliott** [comment]
So with parquet files generated from `2ef012b80dbc` and read from the same commit, I'm struggling to reproduce this issue.

Those same files read by commit `f812768dfa62` basically constantly produce this error. Still unable to reproduce this issue in any kind of contained way I can hand off, but currently trying.

**Comment by joe-elliott** [comment]
I have continued to dig on this with only a bit of luck. The only additional clue I can give at the time is that the panic always occurs on these columns:

```
	StartTimeUnixNano uint64 `parquet:",delta"`
	EndTimeUnixNano   uint64 `parquet:",delta"`
	DurationNanos     uint64 `parquet:",delta"`
```

None of these columns are using a dictionary and should all be using `uint64PageValues` but somehow seem to be using `indexedPage`

**Comment by achille-roussel** [comment]
Was there a schema change at some point which removed the use of dictionary? (maybe some of the files have a historical schema, tho it seems unlikely if you've been testing with recent files).

**Comment by joe-elliott** [comment]
Sadly, nothing so straightforward, the blocks were created from the same schema an hour or so ago.

**Comment by joe-elliott** [comment]
After upgrading to the latest (https://github.com/segmentio/parquet-go/commit/f812768dfa62ced67e9c8591183bf33e8eb35bff -> https://github.com/segmentio/parquet-go/commit/948ea8c65f194e98751f56361b93f14d26411d92) the nature of this issue has changed. Perhaps this will shed some light on what is occurring. 

Example stack trace:
```
github.com/grafana/tempo/pkg/parquetquery.(*ColumnIterator).iterate.func1()
	/home/joe/dev/joe-elliott/tempo/pkg/parquetquery/iters.go:296 +0x58
panic({0x1f3a820, 0xc0471ea168})
	/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/segmentio/parquet-go.newUint64Dictionary(...)
	/home/joe/dev/joe-elliott/tempo/vendor/github.com/segmentio/parquet-go/dictionary.go:1012
github.com/segmentio/parquet-go.(*intType).NewDictionary(0xc049880c80, 0x30, 0x52, {0x3, 0x0, {0xc07d6d6280, 0x260, 0x280}, {0x0, 0x0, ...}})
	/home/joe/dev/joe-elliott/tempo/vendor/github.com/segmentio/parquet-go/type.go:794 +0x593
github.com/segmentio/parquet-go.(*Column).decodeDictionary(0xc04ef55520, {0x30?}, 0x1f8f7e0?, 0x4558fb58?)
	/home/joe/dev/joe-elliott/tempo/vendor/github.com/segmentio/parquet-go/column.go:763 +0x4f4
github.com/segmentio/parquet-go.(*filePages).readDictionaryPage(0xc0734cabe0, 0xc05d1ea330?, 0xc05d1ea330?)
	/home/joe/dev/joe-elliott/tempo/vendor/github.com/segmentio/parquet-go/file.go:584 +0x3f
github.com/segmentio/parquet-go.(*filePages).ReadPage(0xc0734cabe0)
	/home/joe/dev/joe-elliott/tempo/vendor/github.com/segmentio/parquet-go/file.go:522 +0x145
github.com/grafana/tempo/pkg/parquetquery.(*ColumnIterator).iterate.func4(0xc06b38da20, 0xc04558ff50, 0xc04558fec8, {0xc04553a000?, 0x3e8, 0x3e8}, 0x1?, {0x25c08a8, 0xc07c6dd3e0}, {0x25cd7c0, ...})
	/home/joe/dev/joe-elliott/tempo/pkg/parquetquery/iters.go:357 +0x132
github.com/grafana/tempo/pkg/parquetquery.(*ColumnIterator).iterate(0xc06b38da20, {0x25c08a8, 0xc07c6dd3e0}, 0xc07b942678?)
	/home/joe/dev/joe-elliott/tempo/pkg/parquetquery/iters.go:433 +0x565
created by github.com/grafana/tempo/pkg/parquetquery.NewColumnIterator
	/home/joe/dev/joe-elliott/tempo/pkg/parquetquery/iters.go:287 +0x24d
```

Previously the out of bounds values seemed "random" but now they are consistently actually quite close to the actual cap of the slices:

![image](https://user-images.githubusercontent.com/2272392/195119677-0a795930-4663-444a-80dc-7ef894c34cdd.png)

**Comment by achille-roussel** [comment]
Would you be able to share a file that triggers this condition? Or test the file with a different tools?

What I would like to know is whether the condition is expected or not, for example:
* Is the content of the page containing fewer values than declared? (then it could be a problem of the encoding)
* Is the decoder producing fewer values than there are in the page?
* Is it normal under some conditions to have less values than declared (maybe due to nulls)

**Comment by joe-elliott** [comment]
We have determined this is caused by the same bug as #369. I'm still not sure if this bug is in parquet-go or in Tempo's usage of the library. Both of these issues disappear when bufio.Reader pooling is disabled.

Still working to isolate the issue further.

**Comment by joe-elliott** [comment]
This issue was created by a bad return from Tempo. Linked above but I'll include it here as well:

https://github.com/grafana/tempo/pull/1797

If anyone else is seeing similar issues, I would recommend checking the above PR.
